# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='*邮箱地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '用户名已被占用'}, help_text='必填. 不超过18个字符.包含字母,数字和仅有的 @/./+/-/_ only.', max_length=18, unique=True, verbose_name='*用户名'),
        ),
    ]
